language: csharp
mono: none
dotnet: 2.1.504
dist: trusty
sudo: false
addons:
  homebrew:
    packages:
      - openldap
    update: true
before_script:
  - mkdir /tmp/slapd
  - /usr/libexec/slapd -f .test_config/slapd.conf -h ldap://localhost:3389 -d 255 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f .test_config/base.ldif
install:
  - dotnet restore
script:
  - dotnet build LdapForNet.sln
  - dotnet test ./LdapForNet.Tests/
  - dotnet pack
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./LdapForNet/bin/Debug/LdapForNet*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    tags: true
    all_branches: true
    
os:
  - osx
