language: csharp
mono: none
dotnet: 2.1.4
dist: trusty
install:
  - dotnet restore
script:
  - dotnet build LdapForNet.sln
  - dotnet test ./LdapForNet.Tests/
  - dotnet pack
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./LdapForNet/bin/Debug/LdapForNet*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    -    tags: true
    -    all_branches: true
